name: patchwork_workspace
publish_to: none
description: Development workspace for the Patchwork Dart pub package.
repository: https://github.com/medz/patchwork
issue_tracker: https://github.com/medz/patchwork/issues

environment:
  sdk: ^3.10.0

workspace:
  - pub/patchwork

dependencies:
  hooks: ^2.0.2
  patchwork: ^0.6.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.1.0
