import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

final class PubResolutionFixture {
  PubResolutionFixture._(this.root);

  final Directory root;

  String get rootPath => p.normalize(root.path);

  String get appPath => p.join(rootPath, 'pub', 'app');

  String get fooPath => p.join(rootPath, 'cache', 'foo-0.1.0');

  String get fooUpgradePath => p.join(rootPath, 'cache', 'foo-0.1.1');

  String get barPath => p.join(rootPath, 'deps', 'bar');

  String get bazPath => p.join(rootPath, 'git', 'baz');

  String get packageConfigPath {
    return p.join(rootPath, '.dart_tool', 'package_config.json');
  }

  String get lockfilePath => p.join(rootPath, 'pubspec.lock');

  String get packageGraphPath {
    return p.join(rootPath, '.dart_tool', 'package_graph.json');
  }

  static PubResolutionFixture create() {
    final root = Directory.systemTemp.createTempSync('patchwork_pub_');
    final fixture = PubResolutionFixture._(root);
    fixture._write();
    return fixture;
  }

  void dispose() {
    if (root.existsSync()) {
      root.deleteSync(recursive: true);
    }
  }

  void writeFooSource(String content, {String version = '0.1.0'}) {
    final rootPath = version == '0.1.0' ? fooPath : fooUpgradePath;
    Directory(p.join(rootPath, 'lib')).createSync(recursive: true);
    File(p.join(rootPath, 'pubspec.yaml')).writeAsStringSync('''
name: foo
version: $version
''');
    File(p.join(rootPath, 'lib', 'foo.dart')).writeAsStringSync(content);
  }

  void upgradeFooTo011({String content = "String foo() => 'old';\n"}) {
    writeFooSource(content, version: '0.1.1');
    _writePackageConfig(fooRoot: fooUpgradePath);
    _writeLockfile(fooVersion: '0.1.1');
  }

  void pointFooAtAppliedPath(String relativePath) {
    _writePackageConfig(fooRoot: p.join(rootPath, relativePath));
  }

  void _write() {
    Directory(p.join(rootPath, '.dart_tool')).createSync(recursive: true);
    Directory(p.join(appPath, 'lib')).createSync(recursive: true);
    Directory(p.join(barPath, 'lib')).createSync(recursive: true);
    Directory(p.join(bazPath, 'lib')).createSync(recursive: true);

    File(p.join(rootPath, 'pubspec.yaml')).writeAsStringSync('''
name: _
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - pub/*
''');

    File(p.join(appPath, 'pubspec.yaml')).writeAsStringSync('''
name: app

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  foo: 0.1.0
  bar:
    path: ../../deps/bar
  baz:
    git:
      url: https://example.com/baz.git
      ref: main
''');
    File(p.join(appPath, 'lib', 'app.dart')).writeAsStringSync('''
String app() => 'app';
''');

    writeFooSource("String foo() => 'old';\n");
    File(p.join(barPath, 'pubspec.yaml')).writeAsStringSync('''
name: bar
version: 1.0.0
''');
    File(p.join(barPath, 'lib', 'bar.dart')).writeAsStringSync('''
String bar() => 'bar';
''');
    File(p.join(bazPath, 'pubspec.yaml')).writeAsStringSync('''
name: baz
version: 2.0.0
''');
    File(p.join(bazPath, 'lib', 'baz.dart')).writeAsStringSync('''
String baz() => 'baz';
''');

    _writePackageConfig();
    _writeLockfile();
    _writePackageGraph();
  }

  void _writePackageConfig({String? fooRoot}) {
    final packageConfig = {
      'configVersion': 2,
      'packages': [
        {
          'name': 'app',
          'rootUri': p.toUri(appPath).toString(),
          'packageUri': 'lib/',
          'languageVersion': '3.12',
        },
        {
          'name': 'foo',
          'rootUri': p.toUri(fooRoot ?? fooPath).toString(),
          'packageUri': 'lib/',
          'languageVersion': '3.12',
        },
        {
          'name': 'bar',
          'rootUri': p.toUri(barPath).toString(),
          'packageUri': 'lib/',
          'languageVersion': '3.12',
        },
        {
          'name': 'baz',
          'rootUri': p.toUri(bazPath).toString(),
          'packageUri': 'lib/',
          'languageVersion': '3.12',
        },
      ],
    };

    File(packageConfigPath).writeAsStringSync(jsonEncode(packageConfig));
  }

  void _writeLockfile({String fooVersion = '0.1.0'}) {
    File(lockfilePath).writeAsStringSync('''
# Generated by pub
packages:
  bar:
    dependency: "direct main"
    description:
      path: "../../deps/bar"
      relative: true
    source: path
    version: "1.0.0"
  baz:
    dependency: "direct main"
    description:
      url: "https://example.com/baz.git"
      ref: "main"
      resolved-ref: "abc123"
      path: "."
    source: git
    version: "2.0.0"
  foo:
    dependency: "direct main"
    description:
      name: foo
      sha256: ignored-pub-archive-sha
      url: "https://pub.dev"
    source: hosted
    version: "$fooVersion"
sdks:
  dart: ">=3.12.0 <4.0.0"
''');
  }

  void _writePackageGraph() {
    final packageGraph = {
      'roots': ['app'],
      'packages': [
        {
          'name': 'app',
          'dependencies': ['foo', 'bar', 'baz'],
          'devDependencies': <String>[],
        },
        {
          'name': 'foo',
          'version': '0.1.0',
          'dependencies': <String>[],
          'devDependencies': <String>[],
        },
        {
          'name': 'bar',
          'version': '1.0.0',
          'dependencies': <String>[],
          'devDependencies': <String>[],
        },
        {
          'name': 'baz',
          'version': '2.0.0',
          'dependencies': <String>[],
          'devDependencies': <String>[],
        },
      ],
    };

    File(packageGraphPath).writeAsStringSync(jsonEncode(packageGraph));
  }
}
