import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

final class PubResolutionFixture {
  PubResolutionFixture._(this.root);

  final Directory root;

  String get rootPath => p.normalize(root.path);

  String get memberPath => p.join(rootPath, 'pub', 'app');

  String get memberLibPath => p.join(memberPath, 'lib', 'src');

  String get analyzerRootPath => p.join(rootPath, 'cache', 'analyzer-7.4.0');

  String get packageConfigPath {
    return p.join(rootPath, '.dart_tool', 'package_config.json');
  }

  String get lockfilePath => p.join(rootPath, 'pubspec.lock');

  String get packageGraphPath {
    return p.join(rootPath, '.dart_tool', 'package_graph.json');
  }

  static PubResolutionFixture create() {
    final root = Directory.systemTemp.createTempSync(
      'patchwork_pub_resolution_',
    );
    final fixture = PubResolutionFixture._(root);
    fixture._write();
    return fixture;
  }

  void dispose() {
    if (root.existsSync()) {
      root.deleteSync(recursive: true);
    }
  }

  void overwritePackageConfig(String content) {
    File(packageConfigPath).writeAsStringSync(content);
  }

  void writeDuplicatePackageConfig() {
    final packageConfig = {
      'configVersion': 2,
      'packages': [
        {
          'name': 'analyzer',
          'rootUri': p.toUri(analyzerRootPath).toString(),
          'packageUri': 'lib/',
        },
        {
          'name': 'analyzer',
          'rootUri': p.toUri(analyzerRootPath).toString(),
          'packageUri': 'lib/',
        },
      ],
    };

    File(packageConfigPath).writeAsStringSync(jsonEncode(packageConfig));
  }

  void overwriteLockfile(String content) {
    File(lockfilePath).writeAsStringSync(content);
  }

  void overwritePackageGraph(Object? value) {
    File(packageGraphPath).writeAsStringSync(jsonEncode(value));
  }

  void deleteLockfile() {
    File(lockfilePath).deleteSync();
  }

  void deleteAnalyzerRoot() {
    Directory(analyzerRootPath).deleteSync(recursive: true);
  }

  void _write() {
    Directory(p.join(rootPath, '.dart_tool')).createSync(recursive: true);
    Directory(memberLibPath).createSync(recursive: true);
    Directory(p.join(analyzerRootPath, 'lib')).createSync(recursive: true);

    File(p.join(rootPath, 'pubspec.yaml')).writeAsStringSync('''
name: _
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - pub/*
''');

    File(p.join(memberPath, 'pubspec.yaml')).writeAsStringSync('''
name: app

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  analyzer: 7.4.0
''');

    File(p.join(analyzerRootPath, 'pubspec.yaml')).writeAsStringSync('''
name: analyzer
version: 7.4.0
''');

    _writePackageConfig();
    _writeLockfile();
    _writePackageGraph();
  }

  void _writePackageConfig() {
    final packageConfig = {
      'configVersion': 2,
      'packages': [
        {
          'name': 'app',
          'rootUri': p.toUri(memberPath).toString(),
          'packageUri': 'lib/',
          'languageVersion': '3.12',
        },
        {
          'name': 'analyzer',
          'rootUri': p.toUri(analyzerRootPath).toString(),
          'packageUri': 'lib/',
          'languageVersion': '3.4',
        },
      ],
    };

    File(packageConfigPath).writeAsStringSync(jsonEncode(packageConfig));
  }

  void _writeLockfile() {
    File(lockfilePath).writeAsStringSync('''
# Generated by pub
packages:
  analyzer:
    dependency: "direct main"
    description:
      name: analyzer
      url: "https://pub.dev"
    source: hosted
    version: "7.4.0"
sdks:
  dart: ">=3.12.0 <4.0.0"
''');
  }

  void _writePackageGraph() {
    final packageGraph = {
      'roots': ['app'],
      'packages': [
        {
          'name': 'app',
          'version': '0.0.0',
          'dependencies': ['analyzer'],
          'devDependencies': <String>[],
        },
        {
          'name': 'analyzer',
          'version': '7.4.0',
          'dependencies': <String>[],
          'devDependencies': <String>[],
        },
      ],
    };

    File(packageGraphPath).writeAsStringSync(jsonEncode(packageGraph));
  }
}
